"""Add cascade delete

Revision ID: de1b04b9f666
Revises: b5b356a3af38
Create Date: 2025-12-03 11:39:40.600357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de1b04b9f666'
down_revision: Union[str, Sequence[str], None] = 'b5b356a3af38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjectmarks_student_uid'), table_name='subjectmarks')
    op.drop_index(op.f('ix_subjectmarks_uid'), table_name='subjectmarks')
    op.drop_table('subjectmarks')
    op.drop_index(op.f('ix_student_uid'), table_name='student')
    op.drop_index(op.f('name'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', mysql.CHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('student',
    sa.Column('uid', mysql.CHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('average', mysql.FLOAT(), nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'student', ['name'], unique=True)
    op.create_index(op.f('ix_student_uid'), 'student', ['uid'], unique=False)
    op.create_table('subjectmarks',
    sa.Column('uid', mysql.CHAR(length=32), nullable=False),
    sa.Column('student_uid', mysql.CHAR(length=32), nullable=False),
    sa.Column('subject_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('marks_obtain', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_marks', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['student_uid'], ['student.uid'], name=op.f('subjectmarks_ibfk_1')),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_subjectmarks_uid'), 'subjectmarks', ['uid'], unique=False)
    op.create_index(op.f('ix_subjectmarks_student_uid'), 'subjectmarks', ['student_uid'], unique=False)
    # ### end Alembic commands ###
